- Create a `GCP_BUCKET_NAME` on your GCP account and upload "2020-09-11_microparticledata.xlsx"
- Define environment variables including `GCP_SERVICE_ACCOUNT_KEY`, `GCP_PROJECT_ID`, and `GCP_BUCKET_NAME`. 
- Using `google.oauth2` and `google.cloud`, read the .xlsx file from this private bucket.

In [1]:
import os

from dotenv import load_dotenv
from google.oauth2 import service_account
from google.cloud import storage

In [2]:
# Load environment variables from .env file
load_dotenv()

# Access the variables using os.getenv()
service_account_key = os.getenv("GCP_SERVICE_ACCOUNT_KEY")
project_id = os.getenv("GCP_PROJECT_ID")
bucket_name = os.getenv("GCP_BUCKET_NAME")

In [3]:
file_name = "2020-09-11_microparticledata.xlsx"

In [4]:
credentials = service_account.Credentials.from_service_account_file(service_account_key)
# Create a client  to bundle configuration needed for API requests.
client = storage.Client(project=project_id,
                        credentials=credentials)
# Access a bucket 
bucket = client.bucket(bucket_name)
# Access an object (blob) in a bucket
file = bucket.blob(file_name)
# Download
data = file.download_as_bytes()

In [5]:
import io
import pandas as pd

df = pd.read_excel(io.BytesIO(data), sheet_name="fish")

In [6]:
df

,SampleID,StationType_Final,Count,StationCode,SampleDate,Latitude,Longitude,Datum,ProjectCode,EventCode,...,PartsComments,CompositeID,CompositeType,CompositeReplicate,CompositeWeight,UnitCompositeWeight,HomogDate,OrganismGroup,CompAgencyCode,CompositeComments
0,17MMP-AN-CB010-MP_1,Field,33,CB10,2017-07-05,37.906718,-122.346692,WGS84,17-18_MP_Moore,TI,...,NaN,17MMP-AN-CB010-MP_1,Normal,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
1,17MMP-AN-CB010-MP_10,Field,11,CB10,2017-07-05,37.906718,-122.346692,WGS84,17-18_MP_Moore,TI,...,NaN,17MMP-AN-CB010-MP_10,Normal,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
2,17MMP-AN-CB010-MP_2,Field,21,CB10,2017-07-05,37.906718,-122.346692,WGS84,17-18_MP_Moore,TI,...,NaN,17MMP-AN-CB010-MP_2,Normal,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
3,17MMP-AN-CB010-MP_3,Field,18,CB10,2017-07-05,37.906718,-122.346692,WGS84,17-18_MP_Moore,TI,...,NaN,17MMP-AN-CB010-MP_3,Normal,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
4,17MMP-AN-CB010-MP_4,Field,33,CB10,2017-07-05,37.906718,-122.346692,WGS84,17-18_MP_Moore,TI,...,NaN,17MMP-AN-CB010-MP_4,Normal,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,Blank 29-Dec-17,LABQA,8,LABQA,1950-01-01,NaN,NaN,NaN,17-18_MP_Moore,TI,...,NaN,Blank 29-Dec-17,LABQA,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
163,Blank 30-Dec-17,LABQA,2,LABQA,1950-01-01,NaN,NaN,NaN,17-18_MP_Moore,TI,...,NaN,Blank 30-Dec-17,LABQA,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
164,Blank 4-Dec-17,LABQA,3,LABQA,1950-01-01,NaN,NaN,NaN,17-18_MP_Moore,TI,...,NaN,Blank 4-Dec-17,LABQA,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
165,Blank 5-Dec-17,LABQA,6,LABQA,1950-01-01,NaN,NaN,NaN,17-18_MP_Moore,TI,...,NaN,Blank 5-Dec-17,LABQA,1,-88,g,1950-01-01,Fish,UoT-RL,NaN
166,Blank 6-Dec-17,LABQA,3,LABQA,1950-01-01,NaN,NaN,NaN,17-18_MP_Moore,TI,...,NaN,Blank 6-Dec-17,LABQA,1,-88,g,1950-01-01,Fish,UoT-RL,NaN